# Generated by Django 5.1.7 on 2025-03-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_receipt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receipt_image',
        ),
    ]
