# Generated by Django 5.1.7 on 2025-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0002_alter_groupmember_options_expensegroup_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexpense',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact amounts'), ('PERCENTAGE', 'Percentage'), ('SHARES', 'Shares')], default='EQUAL', max_length=10),
        ),
    ]
