# Generated by Django 5.1.7 on 2025-05-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0003_alter_groupexpense_split_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesplit',
            name='is_settled',
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Settlement Requested'), ('confirmed', 'Confirmed by Payee'), ('rejected', 'Rejected by Payee')], default='pending', max_length=20),
        ),
    ]
