# Generated by Django 5.1.7 on 2025-05-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0004_remove_expensesplit_is_settled_expensesplit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroup',
            name='avatar',
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
